version: "3.8"

services:
  api:
    image: librechat/librechat:0.6.9
    restart: always
    env_file:
      - ./.env
    environment:
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
    volumes:
      - /home/skr/projects/MCP-BASE-STACK/services/librechat/config/librechat.yaml:/app/librechat.yaml
      - /home/skr/projects/MCP-BASE-STACK/services/librechat/.env:/app/.env
    ports:
      - "3080:3080"
    depends_on:
      - llm-server
      - mongodb

  llm-server:
    image: ollama/ollama:0.1.27
    restart: always
    volumes:
      - llm_server_data:/root/.ollama
    ports:
      - "11434:11434"

  mongodb:
    image: mongo:6.0.12
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  llm_server_data:
  mongodb_data:
