version: "3.8"

services:
  llm-server:
    image: ollama/ollama:latest
    restart: always
    volumes:
      - llm_server_data:/root/.ollama
      - ../../data/models:/data/models
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_MODELS_PATH=/data/models

volumes:
  llm_server_data:
