tools:
  flake8:
    enabled: true
    config_file: .flake8
    severity_map:
      E: high
      F: critical
      W: medium
      C: low
  pylint:
    enabled: true
    config_file: .pylintrc
    severity_map:
      E: high
      F: critical
      W: medium
      C: low
      R: low
  mypy:
    enabled: true
    config_file: mypy.ini
    severity_map:
      error: high
      note: low
  bandit:
    enabled: true
    severity_map:
      HIGH: critical
      MEDIUM: high
      LOW: medium
  shellcheck:
    enabled: true
    config_file: .shellcheckrc
    severity_map:
      error: high
      warning: medium
      info: low
      style: low

categories:
  code_quality:
    enabled: true
    tools:
      - flake8
      - pylint
  security:
    enabled: true
    tools:
      - bandit
  performance:
    enabled: true
    tools:
      - pylint
  documentation:
    enabled: true
    tools:
      - pylint
    docstring_coverage_threshold: 0.7
  test_coverage:
    enabled: true
    coverage_threshold: 0.8

severity_thresholds:
  critical: 0  # Any critical issues fail the review
  high: 5      # Up to 5 high severity issues allowed
  medium: 10   # Up to 10 medium severity issues allowed
  low: 20      # Up to 20 low severity issues allowed

report:
  detail_level: medium  # high, medium, low
  include_code_snippets: true
  include_suggested_fixes: true
  group_by: category  # category, file, severity

knowledge_graph:
  update: false
  record_issues: true
  record_summary: true