version: "3.8"

services:
  api:
    image: librechat/librechat:latest
    restart: always
    env_file:
      - ./.env
    environment:
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
    volumes:
      - /home/skr/projects/MCP-BASE-STACK/LibreChat/librechat.yaml:/app/librechat.yaml
      - /home/skr/projects/MCP-BASE-STACK/LibreChat/.env:/app/.env
    ports:
      - "3080:3080"
    depends_on:
      - ollama
      - mongodb

  ollama:
    image: ollama/ollama:latest
    restart: always
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"

  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  ollama_data:
  mongodb_data:
