version: "3.8"

services:
  api:
    image: librechat/librechat:latest
    restart: always
    env_file:
      - ./.env
    environment:
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - OLLAMA_API_HOST=http://host.docker.internal:11434
    volumes:
      - /home/skr/projects/MCP-BASE-STACK/LibreChat/librechat.yaml:/app/librechat.yaml
      - /home/skr/projects/MCP-BASE-STACK/LibreChat/.env:/app/.env
    ports:
      - "3080:3080"
    depends_on:
      - mongodb
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_data:
