# Markdownlint configuration
# See https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md for rule details

# Default state for all rules
default: true

# MD013/line-length - Line length
MD013:
  # Number of characters
  line_length: 120
  # Allow long code blocks
  code_blocks: false
  # Allow long tables
  tables: false

# MD033/no-inline-html - Inline HTML
MD033:
  # Allow specific HTML elements
  allowed_elements: ["br", "img", "a", "details", "summary"]

# MD041/first-line-heading/first-line-h1 - First line in a file should be a top-level heading
MD041: false

# MD024/no-duplicate-heading/no-duplicate-header - Multiple headings with the same content
MD024:
  # Allow different nesting levels
  siblings_only: true

# MD029/ol-prefix - Ordered list item prefix
MD029:
  # List style
  style: "one_or_ordered"