name: Dependency Updates

on:
  schedule:
    - cron: "0 0 * * 1" # Run weekly on Monday at midnight
  workflow_dispatch: # Allow manual triggering

jobs:
  update-dependencies:
    name: Check and Update Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for proper analysis

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pip-audit safety

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Run dependency audit
        id: audit
        run: |
          python scripts/utils/maintenance/audit_dependencies.py --verbose --output dependency-audit-report.json
          echo "::set-output name=has_updates::$(jq '.summary.outdated_dependencies > 0' dependency-audit-report.json)"
          echo "::set-output name=has_vulnerabilities::$(jq '.summary.vulnerable_dependencies > 0' dependency-audit-report.json)"

      - name: Create dependency update PR for outdated dependencies
        if: steps.audit.outputs.has_updates == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update outdated dependencies"
          title: "Dependency Updates"
          body: |
            This PR updates outdated dependencies based on the weekly dependency audit.

            ## Changes
            - Updates outdated dependencies to their latest versions
            - Standardizes dependency versions across the project

            ## Audit Report
            The full dependency audit report is attached as an artifact to the workflow run.
          branch: dependency-updates
          base: main
          labels: dependencies,automated-pr

      - name: Create security fix PR for vulnerable dependencies
        if: steps.audit.outputs.has_vulnerabilities == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "fix: update vulnerable dependencies"
          title: "Security: Fix Vulnerable Dependencies"
          body: |
            This PR fixes vulnerable dependencies identified in the weekly dependency audit.

            ## Changes
            - Updates vulnerable dependencies to patched versions

            ## Audit Report
            The full dependency audit report is attached as an artifact to the workflow run.
          branch: dependency-security-fixes
          base: main
          labels: dependencies,security,automated-pr

      - name: Upload audit report
        uses: actions/upload-artifact@v3
        with:
          name: dependency-audit-report
          path: dependency-audit-report.json
