name: MCP Conformance Testing

on:
  push:
    branches: [main, develop]
    paths:
      - "services/mcp-server/**"
      - "scripts/run_conformance_tests.sh"
      - ".github/workflows/mcp-conformance.yml"
  pull_request:
    branches: [main, develop]
    paths:
      - "services/mcp-server/**"
      - "scripts/run_conformance_tests.sh"
      - ".github/workflows/mcp-conformance.yml"
  workflow_dispatch: # Allow manual triggering

jobs:
  conformance-tests:
    name: MCP Protocol Conformance Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run conformance tests
        run: |
          mkdir -p reports
          ./scripts/run_conformance_tests.sh --verbose --report-path=./reports/conformance-report.json

      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: conformance-test-report
          path: reports/conformance-report.json
          retention-days: 14

      - name: Check test results
        run: |
          if [ $(jq -r '.status' ./reports/conformance-report.json) != "PASSED" ]; then
            echo "::error::Conformance tests failed. See the test report for details."
            exit 1
          fi
